# # ingress-nginx has been replaced with envoy-gateway
# ---
# # This is the loadbalancer IP for the ingress-nginx controller.
# apiVersion: cilium.io/v2
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: "ingress-nginx"
# spec:
#   blocks:
#   - cidr: "192.168.99.1/32"
#   serviceSelector:
#     matchExpressions:
#       - {key: io.kubernetes.service.namespace, operator: In, values: ['ingress-nginx']}
---
# This is the loadbalancer IP for the cilium ingress controller.
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: "envoy-gateway"
spec:
  blocks:
  - cidr: "192.168.99.2/32"
  serviceSelector:
    matchExpressions:
      - {key: io.kubernetes.service.namespace, operator: In, values: ['envoy-gateway-system']}
      - {key: gateway.envoyproxy.io/owning-gateway-name, operator: In, values: ['eg']}
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default"
spec:
  blocks:
  - cidr: "192.168.99.128/25"

