apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: "1.18.3"
  install:
    crds: CreateReplace
  interval: 5m
  timeout: 5m
  releaseName: cilium
  targetNamespace: kube-system
  values:
    bgpControlPlane:
      enabled: true
    # enable this to use metallb by default.
    # defaultLBServiceIPAM: none
    envoy:
      enabled: false
    #   nodeSelector:
    #     envoy: "true"
    # gatewayAPI:
    #   enabled: true
    #   secretsNamespace: 
    #     create: true
    #     name: cilium-secrets
    #     sync: true
    #   # externalTrafficPolicy: Local
    #   enableAlpn: true
    # ingressController:
    #   enabled: true
    #   secretsNamespace:
    #     create: true
    #     name: cilium-secrets
    #     sync: true
    #   loadBalancerMode: "shared"
    l7proxy: true
    bpf:
      masquerade: true
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - 100.64.0.0/16
        # generally this should be < 24, maybe /20 or /22 depending on node size.
        # for the rpi cluster here, /24 is plenty since resources are extremely limited.
        clusterPoolIPv4MaskSize: 24
    kubeProxyReplacement: true
    # For k3s, there's a proxy service on each node that 
    # proxies requests to 127.0.0.1:6444 to control-plane
    # nodes :6443
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444
    autoDirectNodeRoutes: true
    ipMasqAgent:
      enabled: true
    nonMasqueradeCIDRs:
    - 100.64.0.0/16
    - 100.65.0.0/16
    loadBalancer:
      mode: dsr
      serviceTopology: true
    routingMode: "native"
    ipv4NativeRoutingCIDR: 100.64.0.0/15
    cgroup:
      autoMount:
        enabled: true
      # hostRoot: /sys/fs/cgroup
    hubble:
      enabled: false
    l2announcements: 
      enabled: false
    externalIPs:
      enabled: true
    devices:
      - eth0
      - eth1
      - enp9s0
