apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-release
      version: "v1.18.6"
  install:
    crds: CreateReplace
  interval: 5m
  timeout: 5m
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  values:
    # -- Kubernetes [`nodeSelector`](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector) to add to the Deployment.
    nodeSelector: 
      role: apps
    # Settings for whether to disable the drivers or other daemons if they are not
    # needed
    csi:
      # -- Enable Snapshotter in CephFS provisioner pod
      enableCephfsSnapshotter: false
      # -- Enable Snapshotter in NFS provisioner pod
      enableNFSSnapshotter: false
      # -- Enable Snapshotter in RBD provisioner pod
      enableRBDSnapshotter: false
    monitoring:
      # -- Enable monitoring. Requires Prometheus to be pre-installed.
      # Enabling will also create RBAC rules to allow Operator to create ServiceMonitors
      enabled: true
