apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: "0.26.1"
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 5m
  timeout: 5m
  releaseName: cnpg
  targetNamespace: cnpg-system
