---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: envoy
  namespace: flux-system
spec:
  interval: 5m
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: 1.5.4
