FROM ubuntu:latest
LABEL maintainer="alphabet5"

RUN apt-get update && apt-get install -y \
    sudo \
    git \
    curl \
    wget \
    vim \
    nano \
    openssh-server \
    iputils-ping \
    net-tools \
    dnsutils \
    lsb-release \
    gnupg2 \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    build-essential \
    iptables \
    iproute2 \
    openvpn \
    wireguard \
    docker.io

