---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chart:
    spec:
      chart: immich
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: immich
      version: "0.10.1"
  interval: 5m
  releaseName: immich
  targetNamespace: immich
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v2.3.1
            env:
              DB_HOSTNAME: "immich-db-rw"
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres
                    key: password
              DB_DATABASE_NAME: "immich"
              REDIS_HOSTNAME: "immich-redis"
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
              IMMICH_TELEMETRY_EXCLUDE: "host,api,io,repo,job"
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: photos
      configuration:
        trash:
          enabled: true
          days: 3650
        storageTemplate:
          enabled: true
          template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
    valkey:
      enabled: false
    server:
      enabled: true
      ingress:
        main:
          enabled: false
    machine-learning:
      enabled: true
      env:
        TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: emptyDir
          accessMode: ReadWriteMany
