---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres
  namespace: immich
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    username: AgA3NGU+18HONjHI2gjl/3O7wNLdwChw9LUUcJACmx3aiMVwmIWzICqbsA9UY0I/XzW+rv6kKc43WYP58mJCvFnh0yoBbosy76LBrkshxNuhQk/CPIQNlszhfQEeNlEo2dLHFhlvH1uT+tznP2ksBR6KBvtUUCYbJbayvFObZjkRb9159wFuTseDSB8xmw1pjaw05BlozrVTiBOHGsAfT9jvz0b0xW11fQjNR5ajjkRRjv6M7TLedvSXUuYpRiYXTRz8qRxGXm4e3vj7iDTuwfLEg4+JINlFyPCb2UD8C0NIuJiE6G40E9D19GZKocANuxnItEoW9imkz9uGjNffuj7zSD1ID/suNRRJx67cOuZkdseCw2rWTgNU2mG8bM5pI9snLoZlxQWDVCxkua2lHz8mDSkckQsgr3ouNPdTBFo/rOwDfjx/3fHgWGjrQOZFClwWJ0/GyodNjl8p3WJpdxGC0YCuiOmYKAhLKHto1WvUNIdmue3gtXHM2cmUQ657cXjsbtZA3QAFobVzpWqbPkB9xwWTAoe0PZmgbYBtl5D4/FGzGOqpc7WCV4mZRX8Hl4Y+dOvSVDMC/iIZnF0e76Cb6EqeIrtuofeDGI4TYqUakrDrk7WCvk4YJsG/7Rp6bWcn8Bg4J5MNapIY09OuwYPhT33I5z2hDVrKtA25IZW7OcrDhmGm7xI4/XSKWPUvtieaY1Was5A=
    password: AgAMd0ii5xrNnhBTOOdvwFF9mj18EUpxEXpuiHd/NZBWNXXI2zyC2Eh41FknfA5XIV38op5Bvw5sIVvmhzXPIcShzcKIhL3dyaEBaJIN7iNnCat5rjZT/Pl+rnoUijmQdNS8O5jWos6D7ugzgsfeTRmRf7WBvTjLoOZTsqtf2zs+NmsCSx0K3h+fBI7wLzZuRrEXzNoa2De/fPA51URwXzjRqOnUUSNSjcO1g/1UCe0NvTe4+iNC1/KgbUhmXNZHqo/ivexpH2HgjDWRNn1aAsXBXUNB7n2soaIdhaHRHmsRrliKvVG6hWxgYGPuuRLWrq+T48NdHqEGentABD8Jqbc6SMvG4VheClD+vWXPYCPhtCJ8R4qFWUWlojt5pu/qliNgeLuDySMic6CfP41jFtCtDFK5WOcRgtAid5RRR0TDY9uvgwnxlE4PwOY+gUgFzGYSgTpJ+GbbRxs8Ft8PZmxQd6zdLmGTGOE+AbL6wGMVUjSurkZVcWoysl1towHTBOqrG6WZu/ZkY8qdAuO6xWSRYBpySelB50TgxugeO9qMu9KPwM+RfSVi0XWEOOOltMgLbQBxS7F0vkCzky8lweCdJzgXQhzyY7uRHWLAxst7bNCUk8w+aTFB87YGO3DJZJqp1DTpOb+KwX7fTapAnnY+Vc9AdBhaq3NrZhkzyo8U6H0ujAqq8kxF8s7rrZCVQJxtZjJReiU=
  template:
    metadata:
      name: immich-postgres
      namespace: immich
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
