---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: photos
  volumeMode: Filesystem
  storageClassName: ""
