---
apiVersion: v1
kind: Secret
metadata:
  name: update-script
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/bash
    set -eu
    # verify that other nodes have bgp enabled before proceeding. If this isn't true, something is wrong and broken.
    all_enabled_count="$(
      kubectl get nodes -l enable-bgp=true -o jsonpath='{.items[*].metadata.name}' \
      | tr ' ' '\n' | grep -c .
    )"
    echo "BGP-enabled nodes: $all_enabled_count (need >= 4)"
    if [ "$all_enabled_count" -lt "4" ]; then
      echo "Not enough other BGP-enabled nodes; skipping upgrade on $SYSTEM_UPGRADE_NODE_NAME."
      exit 1
    fi
    # Remove the enable-bgp label to disable cilium BGP on this node
    # This happens after the node is drained, so there should be no local pods that are receiving traffic.
    # We do this first so that when the node comes back up it doesn't try to re-advertise routes before it's ready, and to prevent
    # traffic from trying to be sent here while it's rebooting / before the bgp grace period expires.

    echo "Removing enable-bgp label from node $SYSTEM_UPGRADE_NODE_NAME"
    kubectl label node "$SYSTEM_UPGRADE_NODE_NAME" enable-bgp=false --overwrite
    echo "Waiting 15 seconds for BGP sessions to drop"
    sleep 15

    # Run upgrade/update inside of chroot /host
    chroot /host /bin/sh -s <<'HOST'
    set -eu
    export DEBIAN_FRONTEND=noninteractive

    apt-get -y update
    apt-get -y --with-new-pkgs \
      -o Dpkg::Options::="--force-confdef" \
      -o Dpkg::Options::="--force-confold" upgrade
    apt-get -y autoremove

    # record whether the host wants a reboot
    if [ -f /var/run/reboot-required ]; then
      touch /reboot-required-marker
    fi
    HOST

    #If a reboot is needed, do it from chroot and bail so the plan re-runs
    if [ -f /host/var/run/reboot-required ]; then
      echo "Rebooting host..."
      chroot /host reboot
      # non-zero so SUC re-runs this plan after the node returns
      exit 1
    fi
    # re-enable bgp on this node
    echo "Re-enabling enable-bgp label on node $SYSTEM_UPGRADE_NODE_NAME"
    kubectl label node "$SYSTEM_UPGRADE_NODE_NAME" enable-bgp=true --overwrite
    echo "Update complete, no reboot required"
    echo "Uncordoning node $SYSTEM_UPGRADE_NODE_NAME"
    kubectl uncordon "$SYSTEM_UPGRADE_NODE_NAME"
    exit 0
