---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cf-api-token
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    CF_API_TOKEN: AgCb67eL9ctwzBynTU83k4xZgMaPOKyGg6sVimtjy1M7RirwAWZH3f0VbdrJrchslwoSoTqp8WXBG38Z73FQ/cAeFR8k0nvv4eLWQJsgUpVLRpYIczXF976hoWpvQSeWn+opUi8deV4rhCKKP6ZLZnQBSUVTdxqxhby2HXOmR6cM6e6J49yJ/e/Tg3vZxNfPdNH1zOC7ucI9CpoZU13kT598blmaJoQ8m8QZLQC6lYeENQxm2YxCqNyJzWNkkEouhgtSWNMlkeS4/yQLzuOMlw4B/VAg08gdtcoLaS1yO6fRa/L2agNCM1l65PsU3WNXtLeoz9cKe2tyTlln2X9wfsMIl/1DjDzkn5rkD/O6d0YdZSTdgRz3iZrFsOP9aMF13CfBGosuVpV5CT7J0M72+YatZzIBXxu6dUjcY5HKC2Bq40TiitG6WvhD9S9b+Ccvbfhk3SJd54WTQZuyjzIiZtapZjKC9vOUei4+ZPKzi0PB+t6zbTmk60j0myj8zbtm1MmE4ZoC4zd+BKGjHOyPauu9ShuHKOQ4ziaWQRQ8wKHkc/4c8UedkkND9H4r+ZH201nXrTOatcQe2vYjoWqJyiw0jCvSDtZi7F/rTbMvWypjCv85PUiUIST5gb+DdZ5K/9AZu0MHK9JLCNKxPka3webbdVSxT09rhXMKuGxssjI8af3I+6dfRZ9qRxnTdF1p8F3jEAedImZ8yEbN1e3lHAv+BLIuS0Z1Or5faWdET1eKIFhJDDwGF40/
  template:
    metadata:
      name: cf-api-token
      namespace: cert-manager
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
